name: Publish Nuget Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_VER: 0.0.${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x          
    
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:Version=${{ env.BUILD_VER }}   
     
      - name: Test
        run: dotnet test src/*.UnitTests/*.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
        
      - name: Mutation Test
        working-directory: src
        run: dotnet stryker
    
      - name: Upload Mutation Report
        uses: actions/upload-artifact@v3.0.0
        with:
          name: mutation-report
          path: src/StrykerOutput
          
      - name: Pack
        run: dotnet pack --no-build --configuration Release /p:Version=${{ env.BUILD_VER }}
        
      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_GALLERY_API_KEY}}


