name: Publish Nuget Package

on:
  push:
    branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

   
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Get Build Version
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Dotnet Build
        run: dotnet build src/*.sln --no-restore
      
      - name: Dotnet Publish
        working-directory: src
        run: dotnet publish *.sln --no-restore
     
      - name: Dotnet Test (unit tests only)
        run: dotnet test src/*.UnitTests/*.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
      
      #- name: Publish
      #  if: startsWith(github.ref, 'refs/heads/release')
      #  run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_GALLERY_API_KEY}}


